server:
  port: 8082
spring:
  application:
    name: voters_roll
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/votersDB?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true 